In [1]:
import pandas  as pd #Data manipulation
import numpy as np #Data manipulation
import matplotlib.pyplot as plt # Visualization
import seaborn as sns #Visualization
plt.rcParams['figure.figsize'] = [8,5]
plt.rcParams['font.size'] =14
plt.rcParams['font.weight']= 'bold'
plt.style.use('seaborn-v0_8-whitegrid')

In [ ]:
z = np.array([[1, 1, 1], [1, 2, 1], [-1, -2, -2], [-1, -1, -2]])
print(z)
B = np.array([1, 1, 1, 1])
w = np.matmul(np.linalg.inv(np.matmul(z.T, z)), z.T)
w = np.matmul(w, B)
print(w)
x1 = np.array([[1, 1, 1], [1, 2, 1], [1, 2, 2], [1, 1, 2]])
y1 = np.matmul(x1, w)
print(y1) # note: +ve => class 1, else class 2

[[ 1  1  1]
 [ 1  2  1]
 [-1 -2 -2]
 [-1 -1 -2]]
[ 3.  0. -2.]
[ 1.  1. -1. -1.]


In [ ]:

# test
x2 = np.array([[1,1.5, 3], [1, 1.5, -5], [1, 1.5, 0], [1, 0, 1.5]])
y2 = np.matmul(x2, w)
print(y2) # Note: +ve class 1 else class 2

[-3. 13.  3.  0.]
